-- Sync 86 skills
INSERT INTO system.skills (name, slug, description, category, status) VALUES
('verificar-prazo-legal','verificar-prazo-legal','Verifica data proposta ≥10 dias corridos (art. 1431º CC) — nunca negocia','audit','active'),
('gerar-ordem-trabalhos','gerar-ordem-trabalhos','Compila pontos obrigatórios + inputs financeiro + manutencao + Mário','generate','active'),
('draft-convocatoria','draft-convocatoria','Gera texto legal de convocatória com lista de condóminos e permilagem','core','active'),
('verificar-quorum','verificar-quorum','Calcula permilagem presente e valida cada deliberação (maioria simples/unanimidade)','audit','active'),
('redigir-ata','redigir-ata','Estrutura ata com secções obrigatórias, votações por permilagem, deliberações','compose','active'),
('identify-sender','identify-sender','Cruza email/tel com core.pessoas — retorna pessoa_id + edificio_id + fracção','extract','active'),
('classify-intent','classify-intent','Classifica pedido em 12 categorias com score de confiança','classification','active'),
('assess-urgency','assess-urgency','Determina urgência: emergência/urgente/normal com base em conteúdo','core','active'),
('enrich-context','enrich-context','Adiciona histórico do condómino, OTs abertas, mora actual ao brief','core','active'),
('route-to-employee','route-to-employee','Cria inbox_item para employee destino com brief completo e metadata','routing','active'),
('classify-problem-pt','classify-problem-pt','Categoriza descrição em taxonomy V5 + retorna confiança','classification','active'),
('match-prestador-geo','match-prestador-geo','Filtra prestadores por concelho/freguesia + especialidade + rating','matching','active'),
('compose-pedido-msg','compose-pedido-msg','Gera mensagem WhatsApp em PT-PT calibrada ao tom','compose','active'),
('extract-magic-link-token','extract-magic-link-token','Gera magic-link único por pedido com expiry','extract','active'),
('escalate-to-human','escalate-to-human','Sinaliza baixa confiança e pinga Mário no Discord','escalate','active'),
('vision-analyse-foto','vision-analyse-foto','Extrai dados de foto enviada pelo owner','vision','active'),
('monitorizar-prazos-legais','monitorizar-prazos-legais','Verifica 8 tipos de prazo obrigatório por edifício — alertas em cascata 90/60/30/15 dias','monitor','active'),
('calcular-mora-grave','calcular-mora-grave','Capital + juros legais (Euribor 6M + 1pp) desde vencimento — para mora >60 dias','core','active'),
('draft-interpelacao-judicial','draft-interpelacao-judicial','Carta formal de último aviso com cálculo de juros — submete approvals_queue','core','active'),
('verificar-rgpd','verificar-rgpd','Responde pedidos RGPD em prazo (30 dias), verifica audit_log activo','audit','active'),
('calendario-anual-obrigacoes','calendario-anual-obrigacoes','Gera calendário de todas as obrigações legais do ano para cada edifício','core','active'),
('personalizar-template','personalizar-template','Injeta nome, fracção, valor, datas no template aprovado — nunca reescreve conteúdo','compose','active'),
('enviar-email-batch','enviar-email-batch','Chama Resend API para lista de destinatários, com anti-spam e horário correcto','core','active'),
('track-entrega','track-entrega','Regista sent/delivered/bounced por destinatário em v2_condominios.comunicacoes','core','active'),
('gerir-bounces','gerir-bounces','Para cada bounce: cria inbox_item para actualizar contacto na base de dados','manage','active'),
('verificar-aprovacao','verificar-aprovacao','Verifica status=''approved'' em approvals_queue antes de qualquer envio — recusa se não aprovado','audit','active'),
('carousel-canva','carousel-canva','5-7 slides via Canva MCP com design tokens PropTech (cores, tipografia, logo)','generate','active'),
('copy-hormozi','copy-hormozi','Framework Hook→Pain→Solution→Outcome→CTA, hook em <6 palavras, PT-PT obrigatório','core','active'),
('ab-variants','ab-variants','2-3 variantes de headline por peça para teste (mesmo visual, copy diferente)','core','active'),
('adaptacao-multiplataforma','adaptacao-multiplataforma','1:1 Instagram/Facebook, 9:16 Stories, 1.91:1 Feed ads, Google Display (300×250, 728×90)','core','active'),
('stories-sequence','stories-sequence','3-5 slides sequenciais para Instagram Stories com CTA no final','core','active'),
('brief-review','brief-review','Confirma elementos obrigatórios antes de criar: vertical + ICP + mensagem + formato + canal','core','active'),
('briefing-vertical','briefing-vertical','Cria brief completo (ICP, mensagem, budget, canal) antes de invocar criativo-conteudo','compose','active'),
('aprovacao-conteudo','aprovacao-conteudo','Revê cada peça antes de submeter approvals_queue para Mário','core','active'),
('budget-discipline','budget-discipline','Valida ROAS vs. target antes de escalar gasto; para campanha se CAC > limite','core','active'),
('calendario-editorial','calendario-editorial','Plano 4 semanas à frente: orgânico + pago por vertical','core','active'),
('digest-semanal','digest-semanal','KPIs por vertical + recomendação de optimização ao cmo-agent','core','active'),
('ocr-fatura','ocr-fatura','Extrai fornecedor/valor/data/NIF com confiança quantificada — >90% auto, <90% flag','extract','active'),
('classify-document','classify-document','Classifica em 9 tipos (fatura/ata/contrato/apólice/extracto/certidão/planta/correspondência/outro)','classification','active'),
('archive-drive','archive-drive','Upload Drive com path canónico [Edifício]/[Tipo]/[Ano]/[Mês]/[filename_normalizado]','core','active'),
('index-supabase','index-supabase','Regista metadados completos + link Drive permanente em v2_condominios.documentos','core','active'),
('notify-employees','notify-employees','Notifica employee relevante: fatura→financeiro, apólice→seguros, certidão→compliance','core','active'),
('simular-tarifas','simular-tarifas','Compara contrato actual com mercado — calcula poupança €/ano + meses ROI','simulation','active'),
('iniciar-mudanca-comercializador','iniciar-mudanca-comercializador','Prepara formulário ERSE de mudança + submete approvals_queue','core','active'),
('monitorizar-consumo','monitorizar-consumo','Detecta anomalias: consumo >baseline+2σ → flag com análise de causa','monitor','active'),
('gerir-carregadores-ev','gerir-carregadores-ev','Calcula kWh por condómino e draft facturação mensal EV','manage','active'),
('alertar-renovacao-contrato','alertar-renovacao-contrato','Monitora vencimentos 90/60/30 dias — com simulação já preparada','alert','active'),
('certificacao-energetica','certificacao-energetica','Monitoriza validade SCE (10 anos) e agenda renovação com antecedência','compliance','active'),
('gerar-quotas','gerar-quotas','Calcula quota_individual = quota_base × (permilagem/1000) e insere em recebimentos','generate','active'),
('verificar-mora','verificar-mora','Identifica pendentes >7 dias, classifica 1º/2º aviso/grave, gera drafts','audit','active'),
('reconciliar-bancario','reconciliar-bancario','Cruza movimentos extrato_bancario com recebimentos — identifica não reconciliados','core','active'),
('relatorio-mensal','relatorio-mensal','Agrega cobrança, pendentes com aging, pagamentos fornecedores por edifício','core','active'),
('calcular-juros-mora','calcular-juros-mora','Calcula juros legais (Euribor 6M + 1pp) desde data de vencimento','core','active'),
('draft-aviso-mora','draft-aviso-mora','Gera carta de aviso proporcional ao tempo em mora (cordial/formal/grave)','core','active'),
('criar-campanha','criar-campanha','Estrutura Campanha→AdSet→Ad via MCP após approvals_queue aprovado','generate','active'),
('targeting-preciso','targeting-preciso','Audiences por vertical: interesses, lookalike (após 100+ conversões), retargeting separado','core','active'),
('roas-guardian','roas-guardian','Check diário; pausa automática se ROAS <2 após 7 dias; alerta se ROAS <1.5 há >3 dias','core','active'),
('escalonamento-disciplinado','escalonamento-disciplinado','+20% budget só se ROAS ≥3 nos últimos 7 dias, máx 1×/semana','core','active'),
('ab-testing','ab-testing','2-3 variantes de criativo; vencedor (≥100 impressões) recebe 80% do budget','core','active'),
('naming-convention','naming-convention','[VERTICAL]_[OBJECTIVO]_[MÊS-ANO] / [TARGETING]_[LOCALIZAÇÃO] / [CRIATIVO-ID]_[VARIANTE]','core','active'),
('captura-multicanal','captura-multicanal','Meta Lead Forms, Google, formulário website, input manual — com dedup por email','extract','active'),
('scoring-automatico','scoring-automatico','0-100: vertical +20, email válido +15, telefone +10, cargo B2B +15, empresa >10 frac +20, intenção +20, email gratuito B2B -10, sem tel -5','core','active'),
('routing-inteligente','routing-inteligente','≥70 → employee operacional da vertical; 40-69 → nurturing; <40 → qualificar manualmente','core','active'),
('nurturing-sequence','nurturing-sequence','3 emails em 7 dias por vertical (D+0, D+3, D+7) com conteúdo específico. RGPD obrigatório.','core','active'),
('relatorio-cpl','relatorio-cpl','CPL real por canal e vertical, cruzando gasto gestor-ads com leads gerados','core','active'),
('triage-avaria','triage-avaria','Classifica tipo técnico + urgência (emergência/urgente/normal) com base em descrição','triage','active'),
('score-prestador','score-prestador','Calcula score: rating×0.4 + taxa_prazo×0.3 + proximidade×0.2 + disponibilidade×0.1','scoring','active'),
('abrir-ot','abrir-ot','Cria OT com contexto completo — adjudica <€200 ou submete approvals_queue','core','active'),
('acompanhar-ot','acompanhar-ot','Verifica OTs abertas >48h sem update — cria flags proporcionais','core','active'),
('fechar-ot','fechar-ot','Fecha OT, verifica valor final vs. orçamento, lança custo em financeiro-condo','core','active'),
('actualizar-rating-prestador','actualizar-rating-prestador','Actualiza score do prestador com base no resultado e prazo da OT','core','active'),
('route-event','route-event','Classifica evento e delega ao employee correcto com contexto completo','routing','active'),
('parallel-launch','parallel-launch','Lança múltiplos employees em simultâneo para triggers globais (fecho mês)','core','active'),
('execute-approval','execute-approval','Executa aprovações pendentes na queue — invoca comunicacao-condo','core','active'),
('sla-monitor','sla-monitor','Verifica SLAs e cria flags 🔴 para items sem resposta','core','active'),
('daily-digest','daily-digest','Consolida estado de todos os employees em inbox_item resumo para Mário','core','active'),
('publicacao-peak-time','publicacao-peak-time','Instagram 19h-21h (seg-sex) / Facebook 13h-15h (seg-qui) / LinkedIn 08h-09h (ter-qui)','publish','active'),
('hashtag-strategy','hashtag-strategy','10-15 hashtags estratificadas por vertical: 3 nicho, 5 médio, 2 grande','core','active'),
('cross-posting','cross-posting','Adapta caption e formato por plataforma — nunca copia igual de Instagram para LinkedIn','core','active'),
('engagement-monitoring','engagement-monitoring','Likes, shares, comentários, saves — flag ao diretor-marketing se outlier em <24h','core','active'),
('auditar-cobertura','auditar-cobertura','Verifica checklist legal de coberturas obrigatórias por edifício (DL 268/94)','audit','active'),
('alertar-renovacao','alertar-renovacao','Cascata 90/60/30/15 dias com simulação de mercado incorporada','alert','active'),
('simular-seguro','simular-seguro','Compara prémio actual com alternativas — ratio cobertura/prémio','simulation','active'),
('participar-sinistro','participar-sinistro','Prepara formulário completo + prazo legal 8 dias úteis → approvals_queue urgente','core','active'),
('acompanhar-sinistro','acompanhar-sinistro','Monitoriza estado semanal, flag se sem movimento >15 dias','core','active'),
('gerir-seguro-fracoes','gerir-seguro-fracoes','Verifica seguros individuais registados e alerta fracções sem cobertura','manage','active')
ON CONFLICT (slug) DO UPDATE SET description=EXCLUDED.description, category=EXCLUDED.category;

-- Sync 42 integrations
INSERT INTO system.integrations (name, slug, type, enabled, config, status) VALUES
('v2_condominios — assembleias/atas','supabase-v2-assembleias','api',true,'{"description":"assembleias, atas, convocatórias, condóminos","icon":"SB","color":"emerald"}'::jsonb,'active'),
('docs-condo (Dora)','docs-condo','api',true,'{"description":"arquivo de atas aprovadas no Drive","icon":"DC","color":"amber"}'::jsonb,'active'),
('Resend (via Cami)','resend','api',true,'{"description":"envio de convocatórias após aprovação","icon":"RS","color":"cyan"}'::jsonb,'active'),
('core.pessoas','supabase-core-pessoas','api',true,'{"description":"identificar remetente por email/tel","icon":"SB","color":"emerald"}'::jsonb,'active'),
('v2_condominios.historico_pedidos','supabase-v2-historico','api',true,'{"description":"histórico de interacções do condómino","icon":"SB","color":"emerald"}'::jsonb,'active'),
('Email Webhook','email-webhook','webhook',true,'{"description":"incoming email → inbox_item","icon":"EM","color":"blue"}'::jsonb,'active'),
('Portal Condómino','portal-webhook','webhook',false,'{"description":"form submit → inbox_item","icon":"PW","color":"slate"}'::jsonb,'draft'),
('Supabase V1 Core','supabase-v1','api',true,'{"description":"edge functions, RLS, auth","icon":"SB","color":"emerald"}'::jsonb,'active'),
('Supabase V5','supabase-v5','api',true,'{"description":"manutencao schema · realtime","icon":"SB","color":"emerald"}'::jsonb,'active'),
('WhatsApp Cloud','whatsapp','api',true,'{"description":"intake + outreach","icon":"WA","color":"green"}'::jsonb,'active'),
('Moloni','moloni','api',true,'{"description":"recibos fiscais PT","icon":"ML","color":"amber"}'::jsonb,'active'),
('Stripe Connect','stripe','api',false,'{"description":"payments PT — sprint 1E","icon":"SC","color":"purple"}'::jsonb,'draft'),
('PostHog','posthog','api',false,'{"description":"product analytics","icon":"PH","color":"amber"}'::jsonb,'draft'),
('v2_condominios — financeiro + assembleias','supabase-v2-compliance','api',true,'{"description":"recebimentos, assembleias, seguros","icon":"SB","color":"emerald"}'::jsonb,'active'),
('core.imoveis','supabase-core','api',true,'{"description":"edifícios activos e metadata legal","icon":"SB","color":"emerald"}'::jsonb,'active'),
('v2_condominios.comunicacoes','supabase-v2-comunicacoes','api',true,'{"description":"registo de todas as comunicações enviadas","icon":"SB","color":"emerald"}'::jsonb,'active'),
('Vonage SMS','vonage-sms','api',false,'{"description":"SMS para urgências (futuro sprint)","icon":"VM","color":"blue"}'::jsonb,'draft'),
('Canva MCP','canva-mcp','mcp',true,'{"description":"criação e export de designs (carousels, stories, banners)","icon":"CA","color":"rose"}'::jsonb,'active'),
('Google Drive MCP','google-drive-mcp','mcp',true,'{"description":"arquivo de assets por vertical/canal/data","icon":"GD","color":"blue"}'::jsonb,'active'),
('core.campanhas','supabase-core-campanhas','api',true,'{"description":"histórico de peças criadas","icon":"SB","color":"emerald"}'::jsonb,'active'),
('system.inbox_items','system-inbox-items','api',true,'{"description":"entrega de assets ao diretor-marketing","icon":"SB","color":"blue"}'::jsonb,'active'),
('core.leads','supabase-core-leads','api',true,'{"description":"volume e qualidade de leads por vertical","icon":"SB","color":"emerald"}'::jsonb,'active'),
('system.approvals_queue','system-approvals-queue','api',true,'{"description":"conteúdo e gasto para aprovação","icon":"SB","color":"amber"}'::jsonb,'active'),
('v2_condominios — documentos','supabase-v2-docs','api',true,'{"description":"documentos, faturas_ocr, documentos_drive","icon":"SB","color":"emerald"}'::jsonb,'active'),
('Google Drive','google-drive','api',true,'{"description":"arquivo estruturado por edifício/ano/tipo","icon":"GD","color":"blue"}'::jsonb,'active'),
('Anthropic Vision API','anthropic-vision','api',true,'{"description":"OCR de PDFs e imagens de faturas","icon":"AI","color":"purple"}'::jsonb,'active'),
('Email Attachments','email-attachments','api',true,'{"description":"processamento de anexos recebidos por email","icon":"EM","color":"slate"}'::jsonb,'active'),
('v4_energia schema','supabase-v4-energia','api',true,'{"description":"contratos, tarifas, simulações","icon":"SB","color":"emerald"}'::jsonb,'active'),
('v2_condominios.carregadores','supabase-v2-ev','api',true,'{"description":"contagens EV por posto e condómino","icon":"SB","color":"emerald"}'::jsonb,'active'),
('ERSE / Mercado PT','erse-api','api',false,'{"description":"tarifas actuais do mercado liberalizado","icon":"ER","color":"orange"}'::jsonb,'draft'),
('v2_condominios — financeiro','supabase-v2-financeiro','api',true,'{"description":"recebimentos, extrato, faturas","icon":"SB","color":"emerald"}'::jsonb,'active'),
('Toconline','toconline','api',false,'{"description":"contabilidade AT-compliant (Mário TOC)","icon":"TC","color":"blue"}'::jsonb,'draft'),
('Facebook Ads MCP','facebook-ads-mcp','mcp',true,'{"description":"ads_create_campaign, ads_create_ad_set, ads_create_ad, ads_get_ad_entities, ads_insights_performance_trend, ads_insights_anomaly_signal, ads_get_opportunity_score","icon":"FB","color":"blue"}'::jsonb,'active'),
('Meta Leads MCP','meta-leads-mcp','mcp',true,'{"description":"leads de Meta Lead Form Ads em real-time","icon":"FB","color":"blue"}'::jsonb,'active'),
('v5_manutencao schema','supabase-v5-manutencao','api',true,'{"description":"OTs, prestadores, orçamentos","icon":"SB","color":"emerald"}'::jsonb,'active'),
('v2_condominios.fracoes','supabase-v2-fracoes','api',true,'{"description":"localização das avarias","icon":"SB","color":"emerald"}'::jsonb,'active'),
('Schema v2_condominios','supabase-v2','api',true,'{"description":"contexto edifícios activos","icon":"SB","color":"emerald"}'::jsonb,'active'),
('Anthropic API','anthropic','api',true,'{"description":"raciocínio orquestração complexa","icon":"AI","color":"purple"}'::jsonb,'active'),
('core.publicacoes','supabase-core-publicacoes','api',true,'{"description":"registo de publicações + URLs + engagement","icon":"SB","color":"emerald"}'::jsonb,'active'),
('v3_seguros schema','supabase-v3-seguros','api',true,'{"description":"apólices, sinistros, seguradoras","icon":"SB","color":"emerald"}'::jsonb,'active'),
('v2_condominios.seguro_fracoes','supabase-v2-seguros','api',true,'{"description":"seguros individuais das fracções","icon":"SB","color":"emerald"}'::jsonb,'active'),
('Seguradoras PT','seguradoras-api','api',false,'{"description":"propostas e participações (futuro)","icon":"SG","color":"blue"}'::jsonb,'draft')
ON CONFLICT (slug) DO UPDATE SET enabled=EXCLUDED.enabled, config=EXCLUDED.config, status=EXCLUDED.status;

-- Sync 43 recipes
INSERT INTO system.recipes (name, slug, employee_id, trigger, cron_expr, event_pattern, payload_schema, active, status) VALUES
('alerta-assembleia-anual','v2-assembleia-condo-alerta-assembleia-anual','v2.assembleia_condo','cron','0 8 1 * *',NULL,'{}'::jsonb,false,'active'),
('convocar-assembleia','v2-assembleia-condo-convocar-assembleia','v2.assembleia_condo','event',NULL,'pedido_convocatoria','{}'::jsonb,false,'active'),
('redigir-ata-pos-assembleia','v2-assembleia-condo-redigir-ata-pos-assembleia','v2.assembleia_condo','event',NULL,'assembleia_realizada','{}'::jsonb,false,'active'),
('email-intake','v2-atendimento-condo-email-intake','v2.atendimento_condo','event',NULL,'email_webhook','{}'::jsonb,false,'active'),
('portal-intake','v2-atendimento-condo-portal-intake','v2.atendimento_condo','event',NULL,'portal_form_submit','{}'::jsonb,false,'active'),
('intake-conversation','v5-bia-intake-conversation','v5.bia','event',NULL,'whatsapp_cloud_webhook','{}'::jsonb,false,'active'),
('daily-handoff-summary','v5-bia-daily-handoff-summary','v5.bia','cron','0 18 * * *',NULL,'{}'::jsonb,false,'active'),
('weekly-compliance','v2-compliance-condo-weekly-compliance','v2.compliance_condo','cron','0 6 * * 1',NULL,'{}'::jsonb,false,'active'),
('mora-grave-intake','v2-compliance-condo-mora-grave-intake','v2.compliance_condo','event',NULL,'mora_acima_60_dias','{}'::jsonb,false,'active'),
('execute-approved-send','v2-comunicacao-condo-execute-approved-send','v2.comunicacao_condo','event',NULL,'approvals_queue_approved','{}'::jsonb,false,'active'),
('quota-reminder-batch','v2-comunicacao-condo-quota-reminder-batch','v2.comunicacao_condo','cron','0 8 5 * *',NULL,'{}'::jsonb,false,'active'),
('brief-to-assets','v0-criativo-conteudo-brief-to-assets','v0.criativo_conteudo','manual',NULL,NULL,'{}'::jsonb,false,'active'),
('weekly-asset-library','v0-criativo-conteudo-weekly-asset-library','v0.criativo_conteudo','cron','0 16 * * 5',NULL,'{}'::jsonb,false,'active'),
('creative-refresh','v0-criativo-conteudo-creative-refresh','v0.criativo_conteudo','manual',NULL,NULL,'{}'::jsonb,false,'active'),
('weekly-kpi-digest','v0-diretor-marketing-weekly-kpi-digest','v0.diretor_marketing','cron','0 9 * * 1',NULL,'{}'::jsonb,false,'active'),
('monthly-editorial-calendar','v0-diretor-marketing-monthly-editorial-calendar','v0.diretor_marketing','cron','0 10 1 * *',NULL,'{}'::jsonb,false,'active'),
('campaign-launch','v0-diretor-marketing-campaign-launch','v0.diretor_marketing','manual',NULL,NULL,'{}'::jsonb,false,'active'),
('email-attachment-intake','v2-docs-condo-email-attachment-intake','v2.docs_condo','event',NULL,'email_com_anexo','{}'::jsonb,false,'active'),
('upload-intake','v2-docs-condo-upload-intake','v2.docs_condo','event',NULL,'documento_uploaded','{}'::jsonb,false,'active'),
('monthly-energy-close','v2-energia-condo-monthly-energy-close','v2.energia_condo','cron','0 6 1 * *',NULL,'{}'::jsonb,false,'active'),
('quarterly-tariff-audit','v2-energia-condo-quarterly-tariff-audit','v2.energia_condo','cron','0 8 1 1,4,7,10 *',NULL,'{}'::jsonb,false,'active'),
('anomaly-detection','v2-energia-condo-anomaly-detection','v2.energia_condo','event',NULL,'fatura_energia_recebida','{}'::jsonb,false,'active'),
('quota-run','v2-financeiro-condo-quota-run','v2.financeiro_condo','cron','0 6 1 * *',NULL,'{}'::jsonb,false,'active'),
('mora-run','v2-financeiro-condo-mora-run','v2.financeiro_condo','cron','0 9 15 * *',NULL,'{}'::jsonb,false,'active'),
('reconciliacao-run','v2-financeiro-condo-reconciliacao-run','v2.financeiro_condo','cron','0 7 1 * *',NULL,'{}'::jsonb,false,'active'),
('daily-performance-check','v0-gestor-ads-daily-performance-check','v0.gestor_ads','cron','0 8 * * *',NULL,'{}'::jsonb,false,'active'),
('weekly-report','v0-gestor-ads-weekly-report','v0.gestor_ads','cron','0 9 * * 1',NULL,'{}'::jsonb,false,'active'),
('campaign-launch','v0-gestor-ads-campaign-launch','v0.gestor_ads','manual',NULL,NULL,'{}'::jsonb,false,'active'),
('daily-lead-processing','v0-gestor-leads-daily-lead-processing','v0.gestor_leads','cron','0 8 30 * *',NULL,'{}'::jsonb,false,'active'),
('weekly-cpl-report','v0-gestor-leads-weekly-cpl-report','v0.gestor_leads','cron','0 17 * * 5',NULL,'{}'::jsonb,false,'active'),
('nurturing-trigger','v0-gestor-leads-nurturing-trigger','v0.gestor_leads','manual',NULL,NULL,'{}'::jsonb,false,'active'),
('avaria-intake','v2-manutencao-condo-avaria-intake','v2.manutencao_condo','event',NULL,'inbox_item_manutencao','{}'::jsonb,false,'active'),
('ot-followup','v2-manutencao-condo-ot-followup','v2.manutencao_condo','cron','0 9 * * *',NULL,'{}'::jsonb,false,'active'),
('fecho-ot','v2-manutencao-condo-fecho-ot','v2.manutencao_condo','event',NULL,'prestador_confirmou_conclusao','{}'::jsonb,false,'active'),
('monthly-close','v2-orquestrador-condo-monthly-close','v2.orquestrador_condo','cron','0 6 1 * *',NULL,'{}'::jsonb,false,'active'),
('mora-run','v2-orquestrador-condo-mora-run','v2.orquestrador_condo','cron','0 9 15 * *',NULL,'{}'::jsonb,false,'active'),
('daily-check','v2-orquestrador-condo-daily-check','v2.orquestrador_condo','cron','0 7 * * *',NULL,'{}'::jsonb,false,'active'),
('event-intake','v2-orquestrador-condo-event-intake','v2.orquestrador_condo','event',NULL,'inbox_item_created','{}'::jsonb,false,'active'),
('weekly-engagement-digest','v0-publisher-social-weekly-engagement-digest','v0.publisher_social','cron','0 16 * * 5',NULL,'{}'::jsonb,false,'active'),
('monthly-schedule-review','v0-publisher-social-monthly-schedule-review','v0.publisher_social','cron','0 10 1 * *',NULL,'{}'::jsonb,false,'active'),
('monthly-insurance-check','v2-seguros-condo-monthly-insurance-check','v2.seguros_condo','cron','0 7 1 * *',NULL,'{}'::jsonb,false,'active'),
('annual-coverage-audit','v2-seguros-condo-annual-coverage-audit','v2.seguros_condo','cron','0 8 1 1 *',NULL,'{}'::jsonb,false,'active'),
('weekly-sinistros','v2-seguros-condo-weekly-sinistros','v2.seguros_condo','cron','0 9 * * 2',NULL,'{}'::jsonb,false,'active')
ON CONFLICT (slug) DO UPDATE SET trigger=EXCLUDED.trigger, cron_expr=EXCLUDED.cron_expr, event_pattern=EXCLUDED.event_pattern;

-- Junctions employee_skills (87)
INSERT INTO system.employee_skills (employee_id, skill_id)
SELECT v.eid, s.id FROM (VALUES
('v2.assembleia_condo','verificar-prazo-legal'),
('v2.assembleia_condo','gerar-ordem-trabalhos'),
('v2.assembleia_condo','draft-convocatoria'),
('v2.assembleia_condo','verificar-quorum'),
('v2.assembleia_condo','redigir-ata'),
('v2.atendimento_condo','identify-sender'),
('v2.atendimento_condo','classify-intent'),
('v2.atendimento_condo','assess-urgency'),
('v2.atendimento_condo','enrich-context'),
('v2.atendimento_condo','route-to-employee'),
('v5.bia','classify-problem-pt'),
('v5.bia','match-prestador-geo'),
('v5.bia','compose-pedido-msg'),
('v5.bia','extract-magic-link-token'),
('v5.bia','escalate-to-human'),
('v5.bia','vision-analyse-foto'),
('v2.compliance_condo','monitorizar-prazos-legais'),
('v2.compliance_condo','calcular-mora-grave'),
('v2.compliance_condo','draft-interpelacao-judicial'),
('v2.compliance_condo','verificar-rgpd'),
('v2.compliance_condo','calendario-anual-obrigacoes'),
('v2.comunicacao_condo','personalizar-template'),
('v2.comunicacao_condo','enviar-email-batch'),
('v2.comunicacao_condo','track-entrega'),
('v2.comunicacao_condo','gerir-bounces'),
('v2.comunicacao_condo','verificar-aprovacao'),
('v0.criativo_conteudo','carousel-canva'),
('v0.criativo_conteudo','copy-hormozi'),
('v0.criativo_conteudo','ab-variants'),
('v0.criativo_conteudo','adaptacao-multiplataforma'),
('v0.criativo_conteudo','stories-sequence'),
('v0.criativo_conteudo','brief-review'),
('v0.diretor_marketing','briefing-vertical'),
('v0.diretor_marketing','aprovacao-conteudo'),
('v0.diretor_marketing','budget-discipline'),
('v0.diretor_marketing','calendario-editorial'),
('v0.diretor_marketing','digest-semanal'),
('v2.docs_condo','ocr-fatura'),
('v2.docs_condo','classify-document'),
('v2.docs_condo','archive-drive'),
('v2.docs_condo','index-supabase'),
('v2.docs_condo','notify-employees'),
('v2.energia_condo','simular-tarifas'),
('v2.energia_condo','iniciar-mudanca-comercializador'),
('v2.energia_condo','monitorizar-consumo'),
('v2.energia_condo','gerir-carregadores-ev'),
('v2.energia_condo','alertar-renovacao-contrato'),
('v2.energia_condo','certificacao-energetica'),
('v2.financeiro_condo','gerar-quotas'),
('v2.financeiro_condo','verificar-mora'),
('v2.financeiro_condo','reconciliar-bancario'),
('v2.financeiro_condo','relatorio-mensal'),
('v2.financeiro_condo','calcular-juros-mora'),
('v2.financeiro_condo','draft-aviso-mora'),
('v0.gestor_ads','criar-campanha'),
('v0.gestor_ads','targeting-preciso'),
('v0.gestor_ads','roas-guardian'),
('v0.gestor_ads','escalonamento-disciplinado'),
('v0.gestor_ads','ab-testing'),
('v0.gestor_ads','naming-convention'),
('v0.gestor_leads','captura-multicanal'),
('v0.gestor_leads','scoring-automatico'),
('v0.gestor_leads','routing-inteligente'),
('v0.gestor_leads','nurturing-sequence'),
('v0.gestor_leads','relatorio-cpl'),
('v2.manutencao_condo','triage-avaria'),
('v2.manutencao_condo','score-prestador'),
('v2.manutencao_condo','abrir-ot'),
('v2.manutencao_condo','acompanhar-ot'),
('v2.manutencao_condo','fechar-ot'),
('v2.manutencao_condo','actualizar-rating-prestador'),
('v2.orquestrador_condo','route-event'),
('v2.orquestrador_condo','parallel-launch'),
('v2.orquestrador_condo','execute-approval'),
('v2.orquestrador_condo','sla-monitor'),
('v2.orquestrador_condo','daily-digest'),
('v0.publisher_social','publicacao-peak-time'),
('v0.publisher_social','hashtag-strategy'),
('v0.publisher_social','cross-posting'),
('v0.publisher_social','calendario-editorial'),
('v0.publisher_social','engagement-monitoring'),
('v2.seguros_condo','auditar-cobertura'),
('v2.seguros_condo','alertar-renovacao'),
('v2.seguros_condo','simular-seguro'),
('v2.seguros_condo','participar-sinistro'),
('v2.seguros_condo','acompanhar-sinistro'),
('v2.seguros_condo','gerir-seguro-fracoes')
) AS v(eid,slug) JOIN system.skills s ON s.slug = v.slug
ON CONFLICT DO NOTHING;

-- Junctions employee_integrations (70)
INSERT INTO system.employee_integrations (employee_id, integration_id)
SELECT v.eid, i.id FROM (VALUES
('v2.assembleia_condo','supabase-v2-assembleias'),
('v2.assembleia_condo','docs-condo'),
('v2.assembleia_condo','resend'),
('v2.atendimento_condo','supabase-core-pessoas'),
('v2.atendimento_condo','supabase-v2-historico'),
('v2.atendimento_condo','email-webhook'),
('v2.atendimento_condo','portal-webhook'),
('v5.bia','supabase-v1'),
('v5.bia','supabase-v5'),
('v5.bia','whatsapp'),
('v5.bia','resend'),
('v5.bia','moloni'),
('v5.bia','stripe'),
('v5.bia','posthog'),
('v2.compliance_condo','supabase-v2-compliance'),
('v2.compliance_condo','supabase-core'),
('v2.compliance_condo','resend'),
('v2.comunicacao_condo','resend'),
('v2.comunicacao_condo','supabase-v2-comunicacoes'),
('v2.comunicacao_condo','supabase-core-pessoas'),
('v2.comunicacao_condo','vonage-sms'),
('v0.criativo_conteudo','canva-mcp'),
('v0.criativo_conteudo','google-drive-mcp'),
('v0.criativo_conteudo','supabase-core-campanhas'),
('v0.criativo_conteudo','system-inbox-items'),
('v0.diretor_marketing','supabase-core-leads'),
('v0.diretor_marketing','supabase-core-campanhas'),
('v0.diretor_marketing','system-inbox-items'),
('v0.diretor_marketing','system-approvals-queue'),
('v2.docs_condo','supabase-v2-docs'),
('v2.docs_condo','google-drive'),
('v2.docs_condo','anthropic-vision'),
('v2.docs_condo','email-attachments'),
('v2.energia_condo','supabase-v4-energia'),
('v2.energia_condo','supabase-v2-ev'),
('v2.energia_condo','erse-api'),
('v2.energia_condo','resend'),
('v2.financeiro_condo','supabase-v2-financeiro'),
('v2.financeiro_condo','supabase-core'),
('v2.financeiro_condo','toconline'),
('v2.financeiro_condo','resend'),
('v0.gestor_ads','facebook-ads-mcp'),
('v0.gestor_ads','supabase-core-campanhas'),
('v0.gestor_ads','supabase-core-leads'),
('v0.gestor_ads','system-approvals-queue'),
('v0.gestor_ads','system-inbox-items'),
('v0.gestor_leads','supabase-core-leads'),
('v0.gestor_leads','meta-leads-mcp'),
('v0.gestor_leads','supabase-core-campanhas'),
('v0.gestor_leads','resend'),
('v0.gestor_leads','system-inbox-items'),
('v0.gestor_leads','system-approvals-queue'),
('v2.manutencao_condo','supabase-v5-manutencao'),
('v2.manutencao_condo','supabase-v2-fracoes'),
('v2.manutencao_condo','resend'),
('v2.manutencao_condo','whatsapp'),
('v2.manutencao_condo','moloni'),
('v2.orquestrador_condo','supabase-v1'),
('v2.orquestrador_condo','supabase-v2'),
('v2.orquestrador_condo','anthropic'),
('v0.publisher_social','facebook-ads-mcp'),
('v0.publisher_social','canva-mcp'),
('v0.publisher_social','supabase-core-publicacoes'),
('v0.publisher_social','supabase-core-campanhas'),
('v0.publisher_social','system-approvals-queue'),
('v0.publisher_social','system-inbox-items'),
('v2.seguros_condo','supabase-v3-seguros'),
('v2.seguros_condo','supabase-v2-seguros'),
('v2.seguros_condo','seguradoras-api'),
('v2.seguros_condo','resend')
) AS v(eid,slug) JOIN system.integrations i ON i.slug = v.slug
ON CONFLICT DO NOTHING;
