// Catálogo canónico dos 10 AI employees condomínio.
// Espelha .claude/agents/*-condo.md mas só o que a UI precisa.
// Quando o apps/dashboard tiver API de employees, esta lista pode passar
// a vir de lá; por agora hardcoded para evitar coupling cross-app.

export const CONDO_AGENTS = [
  {
    slug: 'orquestrador-condo',
    name: 'Otto',
    role: 'Director ops',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'O',
    model: 'claude-sonnet-4-6',
    version: '1.0',
    trigger: 'event',
    description: 'Coordena todos os AI employees do condomínio. Rota eventos de system.inbox_items e cron schedules.',
  },
  {
    slug: 'financeiro-condo',
    name: 'Fina',
    role: 'Quotas + mora',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'F',
    model: 'claude-sonnet-4-6',
    version: '1.0',
    trigger: 'schedule',
    description: 'Emite quotas mensais (Dia 1) e identifica mora (Dia 15). Reconciliação bancária. Aprovações de avisos em approvals_queue.',
  },
  {
    slug: 'manutencao-condo',
    name: 'Manu',
    role: 'OTs + prestadores',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'M',
    model: 'claude-sonnet-4-6',
    version: '1.0',
    trigger: 'event',
    description: 'Gere ordens de trabalho. Auto-approval <€200, workflow €200-€500, pedidos formais >€500.',
  },
  {
    slug: 'assembleia-condo',
    name: 'Assie',
    role: 'Convocatórias + atas',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'A',
    model: 'claude-sonnet-4-6',
    version: '1.0',
    trigger: 'event',
    description: 'Ciclo de vida de assembleias. Verifica prazo mínimo 10 dias (Art. 1431º CC). Gera convocatórias, agendas, atas estruturadas.',
  },
  {
    slug: 'compliance-condo',
    name: 'Cleo',
    role: 'Prazos legais',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'C',
    model: 'claude-sonnet-4-6',
    version: '1.0',
    trigger: 'schedule',
    description: 'Monitoriza 9+ prazos legais (RGPD, renovações de seguros). Escala mora >90 dias para vias legais.',
  },
  {
    slug: 'comunicacao-condo',
    name: 'Coco',
    role: 'Emails + cartas',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'C',
    model: 'claude-haiku-4-5',
    version: '1.0',
    trigger: 'event',
    description: 'Agente de execução pura. Nunca inicia — executa comunicações aprovadas via approvals_queue (Resend, SMS, cartas).',
  },
  {
    slug: 'docs-condo',
    name: 'Dora',
    role: 'OCR + arquivo',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'D',
    model: 'claude-sonnet-4-6',
    version: '1.0',
    trigger: 'event',
    description: 'OCR de faturas, classificação automática, arquivo em Google Drive. Única autorizada a escrever em documentos.',
  },
  {
    slug: 'energia-condo',
    name: 'Enzo',
    role: 'Contratos + EV',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'E',
    model: 'claude-sonnet-4-6',
    version: '1.0',
    trigger: 'schedule',
    description: 'Áreas comuns. Monitorização de contratos, simulação de tarifas, leituras de carregadores EV no Dia 1.',
  },
  {
    slug: 'seguros-condo',
    name: 'Selma',
    role: 'Apólices + sinistros',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'S',
    model: 'claude-sonnet-4-6',
    version: '1.0',
    trigger: 'event',
    description: 'Apólices obrigatórias edifício + multirriscos. Sinistros sempre com aprovação Mário.',
  },
  {
    slug: 'atendimento-condo',
    name: 'Ana',
    role: 'Triagem pedidos',
    vertical: 'V2',
    status: 'idle',
    avatarInitial: 'A',
    model: 'claude-sonnet-4-6',
    version: '1.0',
    trigger: 'event',
    description: 'Triagem automática de pedidos de condóminos. Roteia para agentes especializados.',
  },
]

export function findAgent(slug) {
  return CONDO_AGENTS.find(a => a.slug === slug) || null
}
